In [4]:
import pandas as pd



caminho_cancelados = '../data/item-cancelado-ANONIMO.csv'
caminho_vendas_atend = '../data/venda-produto-atendente-ANONIMO.csv'
caminho_vendas_prod = '../data/venda-produto.csv'

df_canc = pd.read_csv(caminho_cancelados, sep=';')

df_vendas_atend = pd.read_csv(caminho_vendas_atend, sep=';')

df_vendas_prod = pd.read_csv(caminho_vendas_prod, sep=';')

In [5]:
df_canc

,Setor,Data do Cancelamento,Data da Venda,Nome Atendente,Operador Cancelamento,Grupo,Subgrupo,Cód. Produto,Nome do Produto,Quantidade,Preço,Valor,Valor de Custo,Motivo
0,Mesa/Cartão: 103,"12/10/2026, 16:46","12/10/2026, 14:15",Garçom_1,Gerente_1,CARDÁPIO - ALIMENTOS,ENTRADAS,1.0,BATATA FRITA,2.0,"R$ 36,00","R$ 72,00","R$ 0,00",CLIENTE DESISTIU
1,Mesa/Cartão: 14,"12/10/2026, 16:23","12/10/2026, 15:28",Garçom_2,Gerente_1,CARDÁPIO - BEBIDAS,BEBIDAS NÃO ALCOÓLICAS,75.0,REFRIGERANTE (KS),1.0,"R$ 8,00","R$ 8,00","R$ 0,00",CLIENTE DESISTIU
2,Mesa/Cartão: 254,"12/10/2026, 16:01","12/10/2026, 13:12",Garçom_3,Gerente_1,CARDÁPIO - ALIMENTOS,ENTRADAS,1.0,BATATA FRITA,1.0,"R$ 36,00","R$ 36,00","R$ 0,00",CLIENTE DESISTIU
3,Mesa/Cartão: 435,"12/10/2026, 15:53","12/10/2026, 14:18",Garçom_4,Gerente_1,CARDÁPIO - BEBIDAS,BEBIDAS NÃO ALCOÓLICAS,73.0,COCO VERDE,2.0,"R$ 8,00","R$ 16,00","R$ 0,00",ITEM EM FALTA
4,Mesa/Cartão: 299,"12/10/2026, 15:49","12/10/2026, 14:33",Garçom_3,Gerente_1,CARDÁPIO - ALIMENTOS,ENTRADAS,16.0,ISCA DE PEIXE C/ FRITAS,1.0,"R$ 95,00","R$ 95,00","R$ 0,00",CLIENTE DESISTIU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Mesa/Cartão: 280,"03/10/2026, 11:31","03/10/2026, 10:27",Garçom_7,Gerente_2,CARDÁPIO - ALIMENTOS,ENTRADAS,9.0,CARANGUEJO NO COCO,1.0,"R$ 39,00","R$ 39,00","R$ 0,00",CLIENTE DESISTIU
156,Mesa/Cartão: 223,"02/10/2026, 15:05","02/10/2026, 13:03",Garçom_15,Gerente_2,CARDÁPIO - BEBIDAS,BEBIDAS NÃO ALCOÓLICAS,75.0,REFRIGERANTE (KS),1.0,"R$ 8,00","R$ 8,00","R$ 0,00",CLIENTE DESISTIU
157,Mesa/Cartão: 223,"02/10/2026, 13:09","02/10/2026, 13:03",Garçom_15,Gerente_1,CARDÁPIO - ALIMENTOS,REFEIÇÕES,1067.0,PEIXE TILAPIA INTEIRO FRITO,1.0,"R$ 190,00","R$ 190,00","R$ 0,00",ERRO DE LANCAMENTO
158,Mesa/Cartão: 342,"01/10/2026, 14:38","01/10/2026, 10:48",Garçom_8,Gerente_2,CARDÁPIO - ALIMENTOS,REFEIÇÕES,1067.0,PEIXE TILAPIA INTEIRO FRITO,1.0,"R$ 190,00","R$ 190,00","R$ 0,00",VOUCHER
159,159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"R$ 7.412,00","R$ 0,00",NaN

In [6]:
df_vendas_atend

    Atendente       Qtde          Valor
0   Garçom_17     46,000    R$ 1.546,50
1   Garçom_12    264,000    R$ 7.697,00
2    Garçom_3    223,000    R$ 6.149,00
3    Garçom_9    391,000   R$ 11.582,00
4   Garçom_18     13,000      R$ 162,00
5    Garçom_4     93,000    R$ 2.983,00
6   Garçom_13    111,000    R$ 2.344,50
7   Garçom_15    173,000    R$ 5.776,00
8    Garçom_7    319,000    R$ 9.799,50
9    Garçom_5    286,000    R$ 9.640,00
10   Garçom_8    580,000   R$ 20.988,00
11   Garçom_1    324,000   R$ 11.250,00
12  Garçom_10    540,000   R$ 14.191,50
13   Garçom_2    209,000    R$ 5.249,00
14   Garçom_6    283,000    R$ 9.287,00
15  Garçom_14     59,000    R$ 2.018,00
16  Garçom_11    518,000   R$ 18.082,00
17  Garçom_16    346,000   R$ 10.357,50
18  Garçom_19  4.778,000  R$ 149.102,50

In [7]:
df_vendas_prod

,Grupo,Subgrupo,Código,Nome,Quantidade,Valor total
0,Grupo: CARDÁPIO - ALIMENTOS,NaN,NaN,NaN,"1.697,000","R$ 108.993,00"
1,Subgrupo: ENTRADAS,NaN,NaN,NaN,"1.232,000","R$ 63.894,00"
2,CARDÁPIO - ALIMENTOS,ENTRADAS,1.0,BATATA FRITA,159,"R$ 5.724,00"
3,CARDÁPIO - ALIMENTOS,ENTRADAS,4.0,CALDO DE CAMARÃO,86,"R$ 3.010,00"
4,CARDÁPIO - ALIMENTOS,ENTRADAS,5.0,CALDO DE PEIXE,77,"R$ 2.233,00"
...,...,...,...,...,...,...
137,CARDÁPIO - BEBIDAS,VINHOS E ESPUMANTES,118.0,BALDINHO C/ VINHO,3,"R$ 360,00"
138,Grupo: TAXAS E DIVERSOS,NaN,NaN,NaN,"4,000","R$ 200,00"
139,Subgrupo: TAXAS,NaN,NaN,NaN,"4,000","R$ 200,00"
140,TAXAS E DIVERSOS,TAXAS,128.0,SERVIÇO DE ROLHA,4,"R$ 200,00"
141,NaN,NaN,126.0,NaN,NaN,"R$ 149.102,50"